### PR TITLE
Adding remote_theme_cache option to define a cache duration

### PR DESCRIPTION
**Pull request by Morozzzko**
@pixelastic submitted a PR which was stale for a while.

So I forked the repo and merged master manually.

See #27

### CODE REVIEW

**Comment by Morozzzko** [comment]
Feels like `master` would benefit from a newer Rubocop

**Comment by Morozzzko** [comment]
It's been a while since the last activity.

@benbalter any plans on merging it or #37?

**Comment by Morozzzko** [comment]
Any updates?

**Comment by Morozzzko** [comment]
This is bad

**Comment by Morozzzko** [comment]
No

**Comment by pixelastic** [comment]
Any plan on reopening this issue?

**Comment by benbalter** [comment]
Pushed up some now stale, WIP work to move things over to use the Jekyll 4+ cache API. It still needs some work, but would allow users to specify a cache duration: https://github.com/benbalter/jekyll-remote-theme/pull/56.

**Pull request closed without merging**
