### PR TITLE
Add ability to use themes hosted on enterprise GitHub instances.

### LINKED ISSUE #43: Github Enterprise Support
Currently, all the themes can only be downloaded from [a public github](https://github.com/benbalter/jekyll-remote-theme/blob/master/lib/jekyll-remote-theme/downloader.rb#L6). It works great except in the case of enterprise GitHub...would it be possible to use the `github.hostname` provided by `jekyll-github-metadata` to resolve the `HOST` there?

### PR DESCRIPTION
**Pull request by jallenwork**
I'd like to use this for repos hosted in our enterprise instance at work (as would several of my coworkers) so I thought I would throw this against the wall and see if it stuck. I'm not a ruby programmer, so any stylistic feedback is welcome. 
Fixes #43 

-----
[View rendered README.md](https://github.com/jallenwork/jekyll-remote-theme/blob/enterprise/README.md)

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks for this @jallenwork. Curious, do you need to be able to pull from multiple enterprise instances, or could the host be set in the config file as an override?

**Comment by jallenwork** [comment]
I personally don't have any need to use multiple enterprise instances, so for my use case a config file override would work fine. Would you prefer that the host get it's own entry in _config.yml?  
Something like:  
`remote_theme_host: github.<enterprise>.com`

**Comment by benbalter** [comment]
@jallenwork really appreciate the PR. Based on your work, I pushed up a minor refactor that I think makes things a bit more readable and user friendly.

Now, themes can be in the form of `owner/repo` or `http://example.com/owner/repo`.

If no host is supplied, github.com is assumed. 

If a host is supplied, it must be the GitHub Enterprise instance which the site is being built on (to prevent builds on GitHub.com being sent to a malicious server). 

We always download from `codeload.THEME_HOST`.

Does that make sense / meet your needs?

**Comment by jallenwork** [comment]
@benbalter This looks great, thanks for putting in the extra effort on this, I really appreciate it. This should work famously for myself and others running GH Enterprise instances.

**Comment by dmittman** [comment]
From reading through the comments and by administering a GitHub Enterprise Server for a number of years, I think I have an understanding of the requirements for hosting remote themes on GHES, but I thought I'd double-check my understanding.

The comments mention `codeload`, which suggests that your GHES is required to have [subdomain isolation](https://docs.github.com/en/enterprise-server/admin/configuration/configuring-network-settings/enabling-subdomain-isolation) enabled for this approach to work.

Also, the code, I think, mentions that the repo hosting the remote must be "public." The term public can mean a few things, depending on how your GHES is configured, but I'm assuming that it means that the repo hosting the remote theme must not require authentication of any kind.

GHES's that either don't have subdomain isolation enabled or are using [private mode](https://docs.github.com/en/enterprise-server/admin/configuration/configuring-your-enterprise/enabling-private-mode) can't use this approach.

**Pull request merged**
